# 基础镜像
FROM redis
# author
MAINTAINER jingli

# 挂载目录
VOLUME /home/jingli/redis
# 创建目录
RUN mkdir -p /home/jingli/redis
# 指定路径
WORKDIR /home/jingli/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/jingli/redis/redis.conf
